# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 1

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

gomod:
  proxy: false

builds:
  - main: .
    binary: bin/openvpnas_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X 'github.com/elastx/openvpnas_exporter/cmd.Version=v{{ .Version }}'"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

sboms:
  - artifacts: archive

release:
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/elastx/openvpnas_exporter/compare/{{ .PreviousTag }}...{{ .Tag }}
